
// Generated by https://quicktype.io

export interface IUrlshort {
    ok: boolean;
    result: IShortedLink;
}

export interface IShortedLink {
    full_short_link: string;
    original_link: string;
}


export const shortUrl = async (url: string): Promise<IShortedLink> => {
    return new Promise((resolve, reject) => {
        fetch(`https://api.shrtco.de/v2/shorten?url=${url}`)

            .then(response => response.json())
            .then((data) => {
                resolve(data.result);
            }
            )
            .catch(error => {
                reject(error);
            }
            );
    }
    );
}